# myshop/settings.py

"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url  # Import for database configuration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use os.environ.get to retrieve SECRET_KEY from environment variables for production
# Fallback to a default for local development (ensure this is NOT used in production)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-9^!1*a2(x9g$j#y0@)f-o8j!&7z@#j(e^@0i(h+k@m5n=6p')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG should always be False in production for security and performance
# It now defaults to False unless explicitly set to 'True' in an environment variable.
DEBUG = os.environ.get('DEBUG_MODE', 'False') == 'True'  # Changed variable name for clarity and default

# ALLOWED_HOSTS is crucial for security in production.
# Add your Render app's URL here (e.g., 'your-app-name.onrender.com')
# Keep 'localhost' and '127.0.0.1' for local development.
ALLOWED_HOSTS = ['localhost', '127.0.0.1','https://myshopdjango.onrender.com']
# Add your Render app's domain after it's deployed. Example:
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'myshop-django.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admi