# Generated by Django 5.2.5 on 2025-08-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='slides/%Y/%m/%d/')),
                ('link_url', models.URLField(blank=True, help_text="Optional URL for the slide's call-to-action button.", max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which slides appear (lower number first).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide should be displayed in the slideshow.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
